# Generated by Django 3.2 on 2021-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materialandcare',
            field=models.TextField(null=True),
        ),
    ]
