# Generated by Django 3.2 on 2021-06-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderplaced_rent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='rent_duration',
            field=models.CharField(max_length=50),
        ),
    ]
