# Generated by Django 3.2 on 2021-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orderplaced_rent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='rent_duration',
            field=models.CharField(choices=[('4 days', '4 days'), ('8 days', '8 days')], max_length=6),
        ),
    ]
